services:
  app:
    container_name: construct-test
    image: construct-test:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - conf/.env.prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
